// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFznjh4jB8-CyqyCaK3dqdYToADDDHDgA',
    appId: '1:149412134193:web:2a567118f89dc8df68c410',
    messagingSenderId: '149412134193',
    projectId: 'thesisapp-17da9',
    authDomain: 'thesisapp-17da9.firebaseapp.com',
    storageBucket: 'thesisapp-17da9.firebasestorage.app',
    measurementId: 'G-S18JC1L6PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCym91OmCfUFmUkWQd3NRQUfOXLNJKM6ZY',
    appId: '1:149412134193:android:f3a3ec8eaac2141168c410',
    messagingSenderId: '149412134193',
    projectId: 'thesisapp-17da9',
    storageBucket: 'thesisapp-17da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk8qR82FMZlAxc1Wcqvn3BaA5bgNEUS2o',
    appId: '1:149412134193:ios:344fb096ee2a429968c410',
    messagingSenderId: '149412134193',
    projectId: 'thesisapp-17da9',
    storageBucket: 'thesisapp-17da9.firebasestorage.app',
    iosBundleId: 'com.example.thesisapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk8qR82FMZlAxc1Wcqvn3BaA5bgNEUS2o',
    appId: '1:149412134193:ios:344fb096ee2a429968c410',
    messagingSenderId: '149412134193',
    projectId: 'thesisapp-17da9',
    storageBucket: 'thesisapp-17da9.firebasestorage.app',
    iosBundleId: 'com.example.thesisapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFznjh4jB8-CyqyCaK3dqdYToADDDHDgA',
    appId: '1:149412134193:web:90c86d282d212bee68c410',
    messagingSenderId: '149412134193',
    projectId: 'thesisapp-17da9',
    authDomain: 'thesisapp-17da9.firebaseapp.com',
    storageBucket: 'thesisapp-17da9.firebasestorage.app',
    measurementId: 'G-SKB6XJJXLK',
  );
}
